sudo: false
language: node_js
node_js:
  - "6"
  - "8"
  - "10"

script: npm test
before_install:
  - npm config set spin false

install:
  - node --version
  - npm --version
  - git --version
  - npm install --no-optional
